# Doc: http://manuel.manuelles.nl/blog/2012/06/22/integrate-travis-ci-into-grunt/

language: node_js

node_js:
  - 0.8

notifications:
  email:
    recipients:
      - developer@onsip.com
    on_success: change
    on_failure: always
